Improve "show" svg in case where there are many 0D Variables
scipp/scipp pull request #1312
Opened 2020-09-14 15:26 UTC by matthew-d-jones

Closes #1310 

Changes:
- If there are more than 5 0D Variables then only the first and last are drawn as "drawers" and an ellipsis shows that some were omitted.
- Drawer titles are slightly rotated (12 degrees) to avoid overlap.
- Titles longer than 13 characters are truncated to 13 characters and ".." appended. Note, appending the ".." doesn't increase the height of the title, which is the troublesome dimension after the rotation.

![Screenshot_20200914_160418](https://user-images.githubusercontent.com/13455433/93104627-052c1300-f6a6-11ea-9cfd-3c887bdfd8a2.png)

2020-09-15 05:03 UTC, SimonHeybrock reviewed
Builds are failing in the docs, but it looks like a broken Mantid package? @DanNixon any idea what this boost issue could be?

2020-09-15 05:03 UTC, SimonHeybrock commented on python/src/scipp/show.py
> +                        content, width, height, offset, layout_direction, item)
Could this be simplified by conditionally replacing `aread[1:-1]` with the ellipses?

2020-09-15 10:45 UTC, SimonHeybrock approved these changes

2020-09-16 04:51 UTC, SimonHeybrock requested changes
Looking at the docs from the build artifacts: The rotation causes labels to exceed the top of the image (see "Data Structures" doc page). Maybe just set rotation to zero and think about a fix later, so we don't spend excessive amount of time on this, provided that most of the docs look ok?

2020-09-16 06:35 UTC, matthew-d-jones commented
@SimonHeybrock Agreed. It's a shame; it looked good on the real files that I tried, but terrible on much of the docs.

2020-09-16 09:29 UTC, SimonHeybrock commented
Something is not right, for variables it is truncating the dims/shape listed as "title"?

2020-09-16 13:37 UTC, merged