Add "bucketby"
scipp/scipp pull request #1352
Opened 2020-10-20 11:58 UTC by SimonHeybrock

This adds `bucketby`. The current naming is inspired by `groupby`, which does essentially the same except for not executing the reorder into group (instead `groupby` keeps indices of all group contributions). There is a multitude of applications for this:

- Convert raw loaded event data to the "standard" event data layout with data sorted according to pixel ids (this is not really supported yet, would need to add a variant that works with a normal (integer) coord instead of bins, similar to the two variants we have for `groupby`).
- Group event data by pulse-time or TOF.
- Create the equivalent of a Mantid `MDEventWorkspace`.

The performance of this inial implementation is likely very poor. This is a vast number of ooptions for improving this, both in terms of improving the current algorithm, as well as using completely different algorithms. Since the targe applications vary so widely and the use is to important, it may eventually even be necessary to have multiple optimized implementations internally.

Reviewers:
- Check that the plot for bucketed data is back to how it looked before (screenshot kindly provided by Neil: https://github.com/scipp/scipp/pull/1337#discussion_r503855604).
- Try it out. Note that most sanity checks are missing right now, and testing is nearly non-existant, will add those in PR updates or follow-up PRs.
- Maybe focus on the bigger picture for now (docs working again?), internals are likely to be rewritten as missing variants are added and performance gets improved.

2020-10-20 19:20 UTC, OwenArnold requested changes
Quite a few warnings have appeared on apple clang. I'll push a few fixes.

2020-10-20 19:20 UTC, OwenArnold commented on dataset/include/scipp/dataset/bucketby.h
> +SCIPP_DATASET_EXPORT DataArray sortby(const DataArrayConstView &data,
sorby exported but not exposed to python, that would come later?

2020-10-21 04:46 UTC, SimonHeybrock commented on dataset/include/scipp/dataset/bucketby.h
> +SCIPP_DATASET_EXPORT DataArray sortby(const DataArrayConstView &data,
See PR message, I was considering removing it.

2020-10-21 04:54 UTC, SimonHeybrock commented on dataset/test/bucketby_test.cpp
> +#include "scipp/dataset/string.h"
Our `operator<<` is in there (we should probably change that). Without it gtest failures just print byte patterns.

2020-10-21 05:15 UTC, SimonHeybrock commented on python/buckets.cpp
> +  m.def("bucketby", dataset::bucketby,
I would suggest to wait until we have settled on a signature and naming convention.

2020-10-21 12:00 UTC, OwenArnold approved these changes
All comments addressed.

2020-10-21 12:01 UTC, OwenArnold commented
@Matthew-Andrew I believe you had a review in progress too.

2020-10-21 12:01 UTC, merged

2020-10-21 12:02 UTC, SimonHeybrock commented
> @Matthew-Andrew I believe you had a review in progress too.

Sorry for merging early, happy to address more comments in future PRs!