Better SVG repr for binned data
scipp/scipp pull request #1765
Opened 2021-03-11 13:38 UTC by SimonHeybrock

Fixes #1384.

Just like what we had before this formats things badly in many cases, but probably this is better than nothing? Here is how it looks for Mantid-style event data:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/12912489/110795738-7a545b80-8277-11eb-90c9-cd98fe7e7816.png">

2021-03-15 09:30 UTC, nvaytet requested changes
This looks fine overall.
The dashed lines indicating the inset don't always fit if you have many coords and masks, but i don't think it's so important to get this exactly right.
I don't think it will be used so often in practise for large even data files. The html repr is more useful for this.
![Screenshot at 2021-03-15 09-28-14](https://user-images.githubusercontent.com/39047984/111132237-67909e00-8579-11eb-9be4-204cae1fd459.png)

2021-03-15 09:32 UTC, SimonHeybrock commented on python/src/scipp/html/formatting_html.py
> +                f'DataArray(dims=[{dims}], unit={unit}, coords=[{coords}])')
But there may be multiple (if it is not a scalar attribute). So I need at least some sort of braces or brackets?

```python
{dims:[time: 2], uni:=m, coords:...}
```

2021-03-15 09:33 UTC, SimonHeybrock commented on python/src/scipp/show.py
> +        for x, y in 0.1 + 0.8 * np.random.rand(7, 2) + np.array([x0, y0]):
Yes, been considering that, came to the same conclusion as you did. Especially since we often have empty bins at start and end of workspaces.

2021-03-15 13:00 UTC, nvaytet commented on python/src/scipp/html/formatting_html.py
> +                f'DataArray(dims=[{dims}], unit={unit}, coords=[{coords}])')
You mean if you had a 1d variable containing, e.g., 10 data arrays?
And i guess they can all have different dimensions?

2021-03-15 13:00 UTC, SimonHeybrock commented on python/src/scipp/html/formatting_html.py
> +                f'DataArray(dims=[{dims}], unit={unit}, coords=[{coords}])')
Yes, can all be different.

2021-03-16 06:10 UTC, SimonHeybrock commented on python/src/scipp/html/formatting_html.py
> +            unit = f'{elem.unit}'.replace('dimensionless', 'one')
Done.

2021-03-16 06:10 UTC, SimonHeybrock commented on python/src/scipp/html/formatting_html.py
> +                f'DataArray(dims=[{dims}], unit={unit}, coords=[{coords}])')
Done, using `{...}` now.

2021-03-16 06:11 UTC, SimonHeybrock commented on python/src/scipp/show.py
> +                self._variable.bins.constituents['data'])[35:-6])  # drop <svg>
Done (not with a regex)

2021-03-16 21:53 UTC, nvaytet approved these changes

2021-03-17 05:42 UTC, merged