Remove 3-d scatter plots support for dense data
scipp/scipp pull request #2053
Opened 2021-07-14 11:17 UTC by SimonHeybrock

Fix #2046.

2021-07-16 12:04 UTC, nvaytet requested changes
Looks good, some small comments

2021-07-16 12:07 UTC, SimonHeybrock commented on docs/visualization/plotting/plotting-nd-data.ipynb
> +    "da.plot(projection='3d', positions='xyz')"
`da.plot(scatter='position')` looks ok, but wouldn't it be odd if the `projection` argument wouldn't work in combination with `scatter`?

2021-07-16 12:08 UTC, SimonHeybrock commented on docs/visualization/plotting/plotting-nd-data.ipynb
> +    "sc.plot(d, projection='3d', positions='dummy-pos')"
Yes, I thought no one can see a 1% opacity difference, but if pixels are overlapping that may not be the case.

2021-07-16 12:19 UTC, nvaytet commented on docs/visualization/plotting/plotting-nd-data.ipynb
> +    "da.plot(projection='3d', positions='xyz')"
I guess the idea would be to try and remove the `projection` argument altogether?
Not sure what a good way would be to request a 1d plot...

2021-07-19 10:06 UTC, nvaytet commented on docs/visualization/plotting/plotting-nd-data.ipynb
> +    "da.plot(projection='3d', positions='xyz')"
Should we leave this for now and think of argument names in a later PR?

2021-07-19 10:07 UTC, SimonHeybrock commented on docs/visualization/plotting/plotting-nd-data.ipynb
> +    "da.plot(projection='3d', positions='xyz')"
I'd say so, it is unrelated.

2021-07-19 11:46 UTC, nvaytet approved these changes

2021-07-20 04:02 UTC, merged