Preparations for 0.12 release
scipp/scipp pull request #2443
Opened 2022-02-15 13:47 UTC by SimonHeybrock

2022-02-15 14:04 UTC, nvaytet requested changes

2022-02-15 14:04 UTC, nvaytet commented on tools/release/prepare-release.py
> +        '0.12.1', '0.11.0', '0.10.1', '0.9.0', '0.8.4', '0.7.1', '0.6.1', '0.5.0',
```suggestion
        '0.12.0', '0.11.1', '0.10.1', '0.9.0', '0.8.4', '0.7.1', '0.6.1', '0.5.0',
```

2022-02-16 05:30 UTC, SimonHeybrock commented
@nvaytet I added a new section covering the `unit=None` addition. Can you have another look?

2022-02-16 09:03 UTC, nvaytet approved these changes

2022-02-16 09:46 UTC, merged