Compact string format
scipp/scipp pull request #2625
Opened 2022-06-07 08:32 UTC by jl-wynen

Like #2556 but now merging into main

2022-06-14 13:41 UTC, nvaytet commented on src/scipp/format/formatter.py
> +        # return f"{_format(val, var)}{unt}"
Commented code

2022-06-15 09:11 UTC, nvaytet approved these changes

2022-06-15 09:12 UTC, nvaytet requested changes

2022-06-15 13:54 UTC, jl-wynen commented on tests/format/format_test.py
> +        assert array_string(value, error, unit) == expected
Agree, and #2626. But I am not sure where to put the docs. A dedicated page seems overkill. At least until we have more options. Ideas?

2022-06-16 05:16 UTC, SimonHeybrock commented on tests/format/format_test.py
> +        assert array_string(value, error, unit) == expected
Maybe here: https://scipp.github.io/visualization/representations-and-tables.html? Possibly rename the page?

2022-07-14 13:55 UTC, jl-wynen commented
Added documentation for it

2022-07-14 14:03 UTC, nvaytet commented
The diff looks all messsed up.
Some release notes have disappeared and the notebooks contains some output?
```
"metadata": {
    "pycharm": {
     "name": "#%%\n",
     "is_executing": true
    }
   },
```
?

2022-07-14 14:11 UTC, jl-wynen commented
Looks like I screwed up the merge. I force pushed to overwrite the bad merge commit.

And the notebook metadata should have been stripped by `nbstripout`. When running locally, it seems that it doesn't recurse into the right directory. Need to investigate...

2022-07-18 10:07 UTC, jl-wynen commented
@nvaytet Any more comments?

2022-07-18 10:16 UTC, nvaytet approved these changes
Sorry i had not seen that you fixed the issues.

2022-07-18 10:53 UTC, merged