Support `__bool__` where sensible
scipp/scipp pull request #2695
Opened 2022-07-12 11:41 UTC by SimonHeybrock

Fixes #2691.

2022-07-12 12:38 UTC, nvaytet commented on lib/python/bind_operators.h
> +            "The thruth value of a variable with unit is undefined.");
```suggestion
            "The truth value of a variable with unit is undefined.");
```

2022-07-12 12:38 UTC, nvaytet commented on lib/python/bind_operators.h
> +      return self.template value<bool>() == true;
Is this the part that makes sure we don't have more than one value in the `self`? `self.value` raises if the variable is not 0-D?

2022-07-12 12:38 UTC, nvaytet commented on tests/variable_scalar_test.py
> +    var = sc.scalar(value=1.0, unit=None)
Out of interest, do we support conversion from integer? e.g. `sc.scalar(value=1, unit=None)`

2022-07-12 14:16 UTC, jl-wynen requested changes

2022-07-13 03:54 UTC, SimonHeybrock commented on lib/python/bind_operators.h
> +      return self.template value<bool>() == true;
`bool` cannot have variances.

2022-07-13 07:01 UTC, jl-wynen commented on lib/python/bind_operators.h
> +      return self.template value<bool>() == true;
Right

2022-07-13 07:01 UTC, jl-wynen approved these changes

2022-07-13 07:08 UTC, merged