Add `clear`, `copy` and `popitem` methods to coords, masks, and attrs
scipp/scipp pull request #3014
Opened 2023-01-24 16:22 UTC by nvaytet

Fix #2863

2023-01-25 08:04 UTC, jl-wynen requested changes

2023-01-25 08:04 UTC, jl-wynen commented on lib/python/bind_data_array.h
> +    return py::cast(self.extract(key));
`popitem` should return a tuple of `(key, value)`

2023-01-25 08:07 UTC, jl-wynen reviewed
Please run the stubgen because you made interface changes in C++.

2023-01-25 11:46 UTC, nvaytet commented
> Please run the stubgen because you made interface changes in C++.

Postponing until stub generator is fixed.

2023-02-02 12:28 UTC, nvaytet commented
@jl-wynen I finally got round to re-running the stubgen. Can you take a final look? thanks

2023-02-07 09:59 UTC, jl-wynen approved these changes

2023-02-07 10:18 UTC, merged